version: "3.9"


services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 111

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:111@mongo:27017/

  car-server:
    build: .
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: 111
    command: bash -c "npm run start:prod --port 3001"
    volumes:
      - .:/server
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - mongo-express




