version: "3.9"


services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 111
      MONGO_INITDB_DATABASE: car_main
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: dbAdmin
      ME_CONFIG_BASICAUTH_PASSWORD: Kin11001Mk?
      ME_CONFIG_SITE_COOKIESECRET: 11122211
      ME_CONFIG_SITE_SESSIONSECRET: 222111222
      ME_CONFIG_MONGODB_URL: mongodb://root:111@mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

  car-server:
    build: .
    environment:
      MONGO_USER: carAdmin
      MONGO_PASSWORD: Kin11001Mk?
      MONGO_DB_NAME: car_main
      IS_PRODUCTION: false
      DEFAULT_EMAIL: mkinitcpio.feedback@outlook.com
      DEFAULT_SMTP_EMAIL: 
    restart: always
    volumes:
      - .:/server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - mongo-express




